# Encontrar la transformación lineal entre matrices

In [1]:
from scipy import optimize
import numpy as np

Se define la norma Frobenios de una matriz como la traza del producto entre A transpuesta y A

In [2]:
F = lambda A: np.trace(np.dot(A.T,A))

Se toma la matriz X y Y. Se busca una transformación W de X a Y.

Para esto, obtenemos las dimensiones mXn de las matrices. Se crea una lista de tamaño n que se utilizará para definir la función a optimizar.

In [57]:
X = np.array([[1,2,3],[3,1,2],[4,5,1]])
Y = np.array([[2,-1,3],[1,-3,2],[5,-4,1]])
m,n = X.shape
idx = np.arange(n)

In [58]:
def Fx (w, l=0.5):
    w = w.reshape(n, n) #Reshepea el vector a una matriz de nXn
    w2 = np.abs(w)
    w2[idx, idx] = 0
    return F(np.dot(X, w2) - Y) + l*F(w2)

Se aplica un algoritmo de optimización para encontrar la W que minimize la función.

In [59]:
w = optimize.fmin(Fx, np.ones(n*n))

Optimization terminated successfully.
         Current function value: 34.114004
         Iterations: 816
         Function evaluations: 1220


Y se transforma de nuevo a una matriz de tamaño nXn

In [78]:
W = w.reshape(n, n)
W[idx, idx] = 0
W = np.abs(W)
print W

[[  0.00000000e+00   1.62465373e-08   4.70515002e-01]
 [  9.40236450e-01   0.00000000e+00   6.05749359e-02]
 [  8.12813472e-02   1.37288456e-08   0.00000000e+00]]


Podemos comprobar la transformación.

In [80]:
print np.dot(X,W)
print  F(np.round(np.dot(X,W)) - Y)

[[  2.12431694e+00   5.74330742e-08   5.91664874e-01]
 [  1.10279914e+00   7.61973032e-08   1.47211994e+00]
 [  4.78246360e+00   7.87149949e-08   2.18493469e+00]]
32.0
